### ISSUE TITLE
[IndexDefect] Unhandled exception: index 3071 not in 0 .. 511

### ISSUE THREAD

**Issue by mateuszsokola** [status-im/nimbus-eth1#3227]
Network: Mainnet
CL Client: consensys/teku@25.4.0

Docker compose:
```yaml
  nimbus-eth1:
    image: statusim/nimbus-eth1:master
    container_name: nimbus-eth1
    restart: unless-stopped
    user: "1000:1000"
    depends_on:
      pre-setup-check:
        condition: service_completed_successfully
    volumes:
      - ./besu-data:/data
      - ./jwt:/jwt
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8547:8547"
      - "8551:8551"
      - "30303:30303"
      - "30303:30303/udp"
    command: >
      --network=mainnet
      --data-dir=/data
      --rpc
      --http-address=0.0.0.0
      --ws
      --engine-api
      --engine-api-address=0.0.0.0
      --engine-api-port=8551
      --jwt-secret=/jwt/jwt.hex
      --metrics
      --metrics-address=0.0.0.0
      --metrics-port=9093
      --tcp-port=30303
      --udp-port=30303
      --max-peers=50
    environment:
      - NIMBUS_OPTS=-t:4
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
```

Logs:
```
nimbus-eth1      | INF 2025-04-21 10:10:01.579+00:00 Forkchoice requested sync to new head      topics="beacon engine" number=22316370 hash=4f6a61610724
nimbus-eth1      | /root/nimbus-eth1/execution_chain/evm/state.nim(832) main
nimbus-eth1      | /root/nimbus-eth1/execution_chain/evm/state.nim(820) NimMain
nimbus-eth1      | /root/nimbus-eth1/execution_chain/nimbus_execution_client.nim(272) _ZN23nimbus_execution_client3runE3refIN11nimbus_desc26NimbusNodecolonObjectType_EEN6config10NimbusConfE.constprop.0
nimbus-eth1      | /root/nimbus-eth1/vendor/nim-chronos/chronos/internal/asyncengine.nim(150) _ZN11asyncengine4pollE
nimbus-eth1      | /root/nimbus-eth1/vendor/nim-chronos/chronos/internal/asyncfutures.nim(371) _ZN12asyncfutures14futureContinueE3refIN7futures26FutureBasecolonObjectType_EE
nimbus-eth1      | /root/nimbus-eth1/execution_chain/sync/beacon/worker/headers_staged/staged_collect.nim(144) _ZN26collectAndStashOnDiskCache26collectAndStashOnDiskCacheE3refIN7futures26FutureBasecolonObjectType_EE
nimbus-eth1      | /root/nimbus-eth1/vendor/nimbus-build-system/vendor/Nim/lib/system/chcks.nim(28) raiseIndexError2
nimbus-eth1      | /root/nimbus-eth1/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(53) _ZN6system8sysFatalE8typeDescIN10exceptions11IndexDefectEE6string
nimbus-eth1      | /root/nimbus-eth1/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(345) _ZN6system18rawWriteStackTraceE3varI3seqIN6system15StackTraceEntryEEE
nimbus-eth1      | /root/nimbus-eth1/vendor/nimbus-build-system/vendor/Nim/lib/system/stacktraces.nim(62) _ZN11stacktraces30auxWriteStackTraceWithOverrideE3varI3seqIN6system15StackTraceEntryEEE
nimbus-eth1      | [[reraised from:
nimbus-eth1      | /root/nimbus-eth1/execution_chain/evm/state.nim(832) main
nimbus-eth1      | /root/nimbus-eth1/execution_chain/evm/state.nim(820) NimMain
nimbus-eth1      | /root/nimbus-eth1/execution_chain/nimbus_execution_client.nim(272) _ZN23nimbus_execution_client3runE3refIN11nimbus_desc26NimbusNodecolonObjectType_EEN6config10NimbusConfE.constprop.0
nimbus-eth1      | /root/nimbus-eth1/vendor/nim-chronos/chronos/internal/asyncengine.nim(150) _ZN11asyncengine4pollE
nimbus-eth1      | /root/nimbus-eth1/vendor/nim-chronos/chronos/internal/asyncfutures.nim(371) _ZN12asyncfutures14futureContinueE3refIN7futures26FutureBasecolonObjectType_EE
nimbus-eth1      | /root/nimbus-eth1/execution_chain/sync/beacon/worker/headers_staged/staged_collect.nim(160) _ZN26collectAndStashOnDiskCache26collectAndStashOnDiskCacheE3refIN7futures26FutureBasecolonObjectType_EE
nimbus-eth1      | /root/nimbus-eth1/vendor/nimbus-build-system/vendor/Nim/lib/system/stacktraces.nim(62) _ZN11stacktraces30auxWriteStackTraceWithOverrideE3varI3seqIN6system15StackTraceEntryEEE
nimbus-eth1      | ]]
nimbus-eth1      | [[reraised from:
nimbus-eth1      | /root/nimbus-eth1/execution_chain/evm/state.nim(832) main
nimbus-eth1      | /root/nimbus-eth1/execution_chain/evm/state.nim(820) NimMain
nimbus-eth1      | /root/nimbus-eth1/execution_chain/nimbus_execution_client.nim(272) _ZN23nimbus_execution_client3runE3refIN11nimbus_desc26NimbusNodecolonObjectType_EEN6config10NimbusConfE.constprop.0
nimbus-eth1      | /root/nimbus-eth1/vendor/nim-chronos/chronos/internal/asyncengine.nim(150) _ZN11asyncengine4pollE
nimbus-eth1      | /root/nimbus-eth1/vendor/nim-chronos/chronos/internal/asyncfutures.nim(371) _ZN12asyncfutures14futureContinueE3refIN7futures26FutureBasecolonObjectType_EE
nimbus-eth1      | /root/nimbus-eth1/execution_chain/sync/beacon/worker/headers_staged/staged_collect.nim(161) _ZN26collectAndStashOnDiskCache26collectAndStashOnDiskCacheE3refIN7futures26FutureBasecolonObjectType_EE
nimbus-eth1      | /root/nimbus-eth1/vendor/nimbus-build-system/vendor/Nim/lib/system/stacktraces.nim(62) _ZN11stacktraces30auxWriteStackTraceWithOverrideE3varI3seqIN6system15StackTraceEntryEEE
nimbus-eth1      | ]]
nimbus-eth1      | Error: unhandled exception: index 3071 not in 0 .. 511 [IndexDefect]
nimbus-eth1 exited with code 0
```
