### ISSUE TITLE
Deploy nicely formatted test results to github pages

### ISSUE THREAD

**Issue by jangko** [status-im/nimbus-eth1#676]
stealing idea from https://github.com/status-im/nim-ws:
nim-ws is using github pages to store it's automatically generated test report using this github action plugin.

```yml
- name: Deploy autobahn report.
        if: runner.os == 'macos' && matrix.target.cpu == 'amd64'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./nim-ws/autobahn/reports/servers
```

and you can see the result here: https://status-im.github.io/nim-ws/

what we need is convert our markdown generator to produce something more suitable for display.
